version: '2.4'
services:
  doctl:
    image: omnidapps/doctl
    environment:
      DIGITALOCEAN_ACCESS_TOKEN: ${DIGITALOCEAN_ACCESS_TOKEN}
    network_mode: bridge
  kubectl:
    extends:
      file: ../kubectl/docker-compose.yml
      service: kubectl
